apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: insphere-docs
  description: Internal documentation for InSphere
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: insphere  # ✅ FIXED

---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: insphere
spec:
  type: team
  profile:
    displayName: InSphere Team
  children: []
