apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: insphere-docs
  description: Internal documentation for InSphere
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: platform-team
